tags:
    - name: User - Ratings
      description: Оценки товаров пользователем

paths:
    /user/ratings:
        get:
            summary: Получить свои оценки
            tags: [User - Ratings]
            responses:
                '200':
                    description: Список оценок
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Rating'

    /user/ratings/{productId}:
        post:
            summary: Оценить товар (или обновить оценку)
            tags: [User - Ratings]
            parameters:
                - in: path
                  name: productId
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required: [value]
                            properties:
                                value:
                                    type: number
                                    minimum: 1
                                    maximum: 5
            responses:
                '201':
                    description: Оценка сохранена

        delete:
            summary: Удалить оценку
            tags: [User - Ratings]
            parameters:
                - in: path
                  name: productId
                  required: true
                  schema:
                      type: string
            responses:
                '204':
                    description: Удалено

components:
    schemas:
        Rating:
            type: object
            properties:
                id:
                    type: string
                value:
                    type: integer
                createdAt:
                    type: string
                product:
                    $ref: '#/components/schemas/Product'
