services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: abramov
            POSTGRES_PASSWORD: __________
            POSTGRES_DB: app_db
        expose:
            - '5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        # cap_drop:
        #     - ALL

    backend:
        image: zhlnv/abramov-repo:latest # Образ с Docker Hub
        depends_on:
            - db
        ports:
            - '3000:3000'
        environment:
            DATABASE_URL: postgresql://abramov:__________@db:5432/app_db
        volumes:
            - uploads:/app/uploads
        restart: unless-stopped

volumes:
    pgdata:
    uploads:
