# Базовый образ
FROM node:23-alpine

# Рабочая директория
WORKDIR /app

# Установим openssl для Prisma
RUN apk add --no-cache openssl

# Копируем package.json и tsconfig
COPY package*.json ./
COPY tsconfig.json ./

# Установим все зависимости (включая dev)
RUN npm install

# Копируем остальной код
COPY . .

COPY .env.local ./

# Генерация Prisma Client
RUN npx prisma generate

# Команда по умолчанию
CMD ["npm", "run", "dev"]