FROM node:23-slim

WORKDIR /app

# Установим openssl для Prisma
RUN apt-get update -y && \
    apt-get install -y openssl

# Копируем package.json и lock
COPY package*.json ./
COPY tsconfig.json ./

# Установим все зависимости включая dev
RUN npm install

# Копируем остальной код
COPY . .

RUN npx prisma generate

RUN npm run build

# Команда по умолчанию (запускается из docker-compose)
CMD ["npm", "run", "start"]