services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: abramov
            POSTGRES_PASSWORD: asdfg12345Q
            POSTGRES_DB: app_db
        expose:
            - '5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        image: zhlnv/abramov-repo:latest
        depends_on:
            - db
        ports:
            - '3000:3000'
            - '5555:5555'
        environment:
            DATABASE_URL: postgresql://abramov:asdfg12345Q@db:5432/app_db
        volumes:
            - uploads:/app/uploads
        restart: unless-stopped

volumes:
    pgdata:
    uploads:
