FROM node:23-slim

WORKDIR /app

# Установим openssl для Prisma
RUN apt-get update && apt-get install -y openssl

# Копируем package.json и lock
COPY package*.json ./

# Установим все зависимости включая dev
RUN npm install

# Копируем остальной код
COPY . .

# Команда по умолчанию (запускается из docker-compose)
CMD ["npm", "run", "dev"]