FROM node:23-alpine

WORKDIR /app

# Установим openssl для Prisma
RUN apk add --no-cache openssl

# Копируем package.json и lock
COPY package*.json ./
COPY tsconfig.json ./

# Установим все зависимости включая dev
RUN npm install

# Копируем остальной код
COPY . .

RUN npx prisma generate