services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app_db
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        image: zhlnv/abramov-container
        env_file:
            - .env.local
        depends_on:
            - db
        ports:
            - '3000:3000'
            - '5555:5555'
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db:5432/app_db
        volumes:
            - ./uploads:/app/uploads # Монтуємо uploads
        command: sh -c "mkdir -p uploads && npm run dev"
volumes:
    pgdata:
