tags:
    - name: Admin - Categories
      description: Управление категориями товаров

paths:
    /admin/categories:
        get:
            summary: Получить все категории
            tags: [Admin - Categories]
            responses:
                '200':
                    description: Успешно
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Category'

        post:
            summary: Создать категорию
            tags: [Admin - Categories]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateCategoryDto'
            responses:
                '201':
                    description: Категория создана
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Category'

    /admin/categories/{id}:
        get:
            summary: Получить категорию по ID
            tags: [Admin - Categories]
            parameters:
                - in: path
                  name: id
                  schema:
                      type: string
                  required: true
                  description: ID категории
            responses:
                '200':
                    description: Успешно
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Category'
                '404':
                    description: Категория не найдена

        patch:
            summary: Обновить категорию
            tags: [Admin - Categories]
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateCategoryDto'
            responses:
                '200':
                    description: Обновлено
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Category'

        delete:
            summary: Удалить категорию
            tags: [Admin - Categories]
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
            responses:
                '204':
                    description: Удалено

    /admin/cattree:
        get:
            summary: Получить дерево всех категорий
            tags: [Admin - Categories]
            responses:
                '200':
                    description: Успешно
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/CategoryWithChildren'

    /admin/categories/{id}/children:
        get:
            summary: Получить подкатегории по ID
            tags: [Admin - Categories]
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Список подкатегорий
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Category'

components:
    schemas:
        Category:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                createdAt:
                    type: string
                    format: date-time

        CategoryWithChildren:
            allOf:
                - $ref: '#/components/schemas/Category'
                - type: object
                  properties:
                      children:
                          type: array
                          items:
                              $ref: '#/components/schemas/Category'

        CreateCategoryDto:
            type: object
            required:
                - name
            properties:
                name:
                    type: string
                parentId:
                    type: string
                    nullable: true

        UpdateCategoryDto:
            type: object
            properties:
                name:
                    type: string
                parentId:
                    type: string
                    nullable: true
